/**
 * Writing and resyncing messages.
 *
 * Only the realtime server writes messages (decision D-016), so there is one writer and one order.
 * See docs/architecture/data-model.md, "How a message gets its number".
 */
import { and, asc, eq, gt, inArray, isNull, lte, ne, or, sql, type SQL } from 'drizzle-orm';

import { extractMentions } from '@socketspace/shared/markdown';

import type { Database, Queryable } from '../client';
import { dbNow } from '../clock';
import { isUniqueViolation } from '../errors';
import { newId } from '../schema/_common';
import { user } from '../schema/auth';
import { conversation, conversationMember, roomBan } from '../schema/conversations';
import { mention, message } from '../schema/messages';
import { block } from '../schema/social';
import { userSanction } from '../schema/safety';
import { notifyForMessage, type NotificationRow } from './notifications';

export type MessageRow = typeof message.$inferSelect;

export interface SendMessageInput {
  conversationId: string;
  authorId: string;
  /** Generated by the browser; a re-send with the same ID returns the original message. */
  clientId: string;
  /** Already validated and normalised by the shared contract. */
  body: string;
  replyToId?: string | null;
  /** A fixed clock for tests. Without it, every time check uses the database's own clock. */
  now?: Date;
}

/** Why a send was refused. The realtime server maps these to `FORBIDDEN`, `NOT_FOUND`, etc. */
export type SendRefusal =
  | { reason: 'conversation_not_found' }
  | { reason: 'conversation_archived' }
  | { reason: 'account_inactive' }
  | { reason: 'guest_account' }
  | { reason: 'email_unverified' }
  | { reason: 'not_onboarded' }
  | { reason: 'sanctioned'; until: Date | null }
  | { reason: 'not_member' }
  | { reason: 'muted'; until: Date }
  | { reason: 'room_banned'; until: Date | null }
  | { reason: 'blocked' }
  | { reason: 'reply_not_found' }
  | { reason: 'client_id_conflict' };

export type SendMessageResult =
  | {
      ok: true;
      message: MessageRow;
      duplicate: boolean;
      /** People @mentioned in this message (new messages only; empty for a re-send). */
      mentions: string[];
      /** Notifications this message created (NOTIF-01; empty for a re-send). */
      notifications: NotificationRow[];
    }
  | ({ ok: false } & SendRefusal);

async function findByClientId(
  db: Queryable,
  authorId: string,
  clientId: string,
): Promise<MessageRow | undefined> {
  const [row] = await db
    .select()
    .from(message)
    .where(and(eq(message.authorId, authorId), eq(message.clientId, clientId)));
  return row;
}

function duplicateOrConflict(existing: MessageRow, conversationId: string): SendMessageResult {
  // The same client ID used for a different conversation is a client bug or a probe: refuse it
  // rather than returning a message from another conversation.
  return existing.conversationId === conversationId
    ? { ok: true, message: existing, duplicate: true, mentions: [], notifications: [] }
    : { ok: false, reason: 'client_id_conflict' };
}

/**
 * Saves a message and gives it the conversation's next sequence number, in one transaction:
 *
 * 1. Lock the conversation row (`FOR UPDATE`). This serialises writers in the same conversation,
 *    which is what makes sequence numbers gap-free and ordered.
 * 2. If this author already sent this client ID, return the saved message (idempotent re-send).
 * 3. Check every permission against the current state of the database.
 * 4. Insert the message with `seq = last_event_seq + 1` and move the counter forward.
 *
 * If any check fails, nothing is written.
 */
export async function sendMessage(
  db: Database,
  input: SendMessageInput,
): Promise<SendMessageResult> {
  const clock = dbNow(input.now);
  try {
    return await db.transaction(async (tx) => {
      const [conv] = await tx
        .select({
          id: conversation.id,
          kind: conversation.kind,
          lastEventSeq: conversation.lastEventSeq,
          archivedAt: conversation.archivedAt,
        })
        .from(conversation)
        .where(eq(conversation.id, input.conversationId))
        .for('update');
      if (!conv) return { ok: false, reason: 'conversation_not_found' } as const;

      const existing = await findByClientId(tx, input.authorId, input.clientId);
      if (existing) return duplicateOrConflict(existing, input.conversationId);

      const refusal = await checkCanPost(tx, {
        conversationId: conv.id,
        conversationKind: conv.kind,
        archived: conv.archivedAt !== null,
        authorId: input.authorId,
        replyToId: input.replyToId ?? null,
        clock,
      });
      if (refusal) return { ok: false, ...refusal } as const;

      const seq = conv.lastEventSeq + 1;
      const [saved] = await tx
        .insert(message)
        .values({
          id: newId(),
          conversationId: conv.id,
          seq,
          versionSeq: seq,
          authorId: input.authorId,
          clientId: input.clientId,
          kind: 'text',
          body: input.body,
          replyToId: input.replyToId ?? null,
          createdAt: input.now ?? clock,
        })
        .returning();
      if (!saved) throw new Error('INSERT ... RETURNING returned no row');

      await tx
        .update(conversation)
        .set({ lastEventSeq: seq, lastMessageAt: input.now ?? clock })
        .where(eq(conversation.id, conv.id));
      // Writing in a conversation means you have read it up to here.
      await tx
        .update(conversationMember)
        .set({ lastReadSeq: sql`greatest(${conversationMember.lastReadSeq}, ${seq})` })
        .where(
          and(
            eq(conversationMember.conversationId, conv.id),
            eq(conversationMember.userId, input.authorId),
          ),
        );
      const mentions = await saveMentions(tx, saved);
      const notifications = await notifyForMessage(tx, saved, mentions, {
        conversationKind: conv.kind,
        includeReplyAndDm: true,
      });

      return { ok: true, message: saved, duplicate: false, mentions, notifications } as const;
    });
  } catch (error) {
    // Two copies of the same re-send racing each other: the second hits the unique key on
    // (author_id, client_id). Its transaction rolled back, so nothing was written; return the
    // copy that won.
    if (isUniqueViolation(error, 'message_author_client_uq')) {
      const winner = await findByClientId(db, input.authorId, input.clientId);
      if (winner) return duplicateOrConflict(winner, input.conversationId);
    }
    throw error;
  }
}

export interface PostCheck {
  conversationId: string;
  conversationKind: 'room' | 'dm';
  archived: boolean;
  authorId: string;
  replyToId: string | null;
  clock: SQL;
}

/** Returns the first reason the author may not post here, or `null` if they may. */
export async function checkCanPost(tx: Queryable, check: PostCheck): Promise<SendRefusal | null> {
  if (check.archived) return { reason: 'conversation_archived' };

  const [author] = await tx
    .select({
      status: user.status,
      isAnonymous: user.isAnonymous,
      emailVerified: user.emailVerified,
      onboardedAt: user.onboardedAt,
    })
    .from(user)
    .where(eq(user.id, check.authorId));
  if (author?.status !== 'active') return { reason: 'account_inactive' };
  if (author.isAnonymous) return { reason: 'guest_account' };
  if (!author.emailVerified) return { reason: 'email_unverified' };
  if (!author.onboardedAt) return { reason: 'not_onboarded' };

  const sanctions = await tx
    .select({ expiresAt: userSanction.expiresAt })
    .from(userSanction)
    .where(
      and(
        eq(userSanction.userId, check.authorId),
        eq(userSanction.scope, 'global'),
        inArray(userSanction.kind, ['mute', 'suspend', 'ban']),
        isNull(userSanction.liftedAt),
        lte(userSanction.startsAt, check.clock),
        or(isNull(userSanction.expiresAt), gt(userSanction.expiresAt, check.clock)),
      ),
    );
  if (sanctions.length > 0) {
    const permanent = sanctions.some((s) => s.expiresAt === null);
    const latest = sanctions.reduce<Date | null>(
      (max, s) => (s.expiresAt && (!max || s.expiresAt > max) ? s.expiresAt : max),
      null,
    );
    return { reason: 'sanctioned', until: permanent ? null : latest };
  }

  const [member] = await tx
    .select({
      mutedUntil: conversationMember.mutedUntil,
      muted: sql<boolean>`coalesce(${conversationMember.mutedUntil} > ${check.clock}, false)`,
    })
    .from(conversationMember)
    .where(
      and(
        eq(conversationMember.conversationId, check.conversationId),
        eq(conversationMember.userId, check.authorId),
      ),
    );
  if (!member) return { reason: 'not_member' };
  if (member.muted && member.mutedUntil) {
    return { reason: 'muted', until: member.mutedUntil };
  }

  const [ban] = await tx
    .select({ expiresAt: roomBan.expiresAt })
    .from(roomBan)
    .where(
      and(
        eq(roomBan.conversationId, check.conversationId),
        eq(roomBan.userId, check.authorId),
        or(isNull(roomBan.expiresAt), gt(roomBan.expiresAt, check.clock)),
      ),
    );
  if (ban) return { reason: 'room_banned', until: ban.expiresAt };

  if (check.conversationKind === 'dm') {
    // In a DM, a block in either direction stops new messages.
    const [blocked] = await tx
      .select({ one: sql<number>`1` })
      .from(block)
      .innerJoin(
        conversationMember,
        and(
          eq(conversationMember.conversationId, check.conversationId),
          sql`${conversationMember.userId} <> ${check.authorId}`,
        ),
      )
      .where(
        or(
          and(eq(block.blockerId, conversationMember.userId), eq(block.blockedId, check.authorId)),
          and(eq(block.blockerId, check.authorId), eq(block.blockedId, conversationMember.userId)),
        ),
      )
      .limit(1);
    if (blocked) return { reason: 'blocked' };
  }

  if (check.replyToId) {
    const [target] = await tx
      .select({ id: message.id })
      .from(message)
      .where(
        and(eq(message.id, check.replyToId), eq(message.conversationId, check.conversationId)),
      );
    if (!target) return { reason: 'reply_not_found' };
  }

  return null;
}

/**
 * Records who a message @mentions (MSG-06): nicknames found outside code, matched without regard
 * to letter case, limited to members of the conversation, never the author, and never someone who
 * blocked the author (SAFE-01). Returns the IDs of the people mentioned.
 */
export async function saveMentions(
  tx: Queryable,
  saved: Pick<MessageRow, 'id' | 'conversationId' | 'authorId' | 'body'>,
): Promise<string[]> {
  const nicknames = extractMentions(saved.body);
  if (nicknames.length === 0) return [];
  const people = await tx
    .select({ id: user.id })
    .from(user)
    .innerJoin(
      conversationMember,
      and(
        eq(conversationMember.userId, user.id),
        eq(conversationMember.conversationId, saved.conversationId),
      ),
    )
    .where(
      and(
        inArray(sql`lower(${user.nickname})`, nicknames),
        ne(user.id, saved.authorId),
        sql`not exists (select 1 from ${block}
          where ${block.blockerId} = ${user.id} and ${block.blockedId} = ${saved.authorId})`,
      ),
    );
  const ids = people.map((p) => p.id);
  if (ids.length > 0) {
    await tx
      .insert(mention)
      .values(ids.map((userId) => ({ messageId: saved.id, userId })))
      .onConflictDoNothing();
  }
  return ids;
}

export interface EventsSince {
  /** Messages whose latest change is after the cursor, oldest change first. */
  messages: MessageRow[];
  /** More than `limit` changes were missed: the client should reload the latest page instead. */
  reset: boolean;
}

/**
 * Everything that changed in a conversation after `afterEventSeq` (new messages, edits, deletions,
 * reaction changes), used by `sync:request` after a reconnect.
 */
export async function listEventsSince(
  db: Queryable,
  conversationId: string,
  afterEventSeq: number,
  limit: number,
): Promise<EventsSince> {
  const rows = await db
    .select()
    .from(message)
    .where(and(eq(message.conversationId, conversationId), gt(message.versionSeq, afterEventSeq)))
    .orderBy(asc(message.versionSeq))
    .limit(limit + 1);
  return rows.length > limit ? { messages: [], reset: true } : { messages: rows, reset: false };
}
