/**
 * Building blocks shared by every table definition.
 */
import { customType, pgEnum, timestamp, uuid } from 'drizzle-orm/pg-core';
import { v7 as uuidv7 } from 'uuid';

import {
  ATTACHMENT_STATUSES,
  AVATAR_KINDS,
  COLOR_MODES,
  CONTACT_REQUEST_STATUSES,
  CONTACT_SOURCES,
  CONVERSATION_KINDS,
  CONVERSATION_VISIBILITIES,
  DELETED_BY,
  DM_POLICIES,
  FLAG_SEVERITIES,
  FLAG_SOURCES,
  LINK_PREVIEW_STATUSES,
  MEMBER_ROLES,
  MESSAGE_KINDS,
  MODERATION_ACTION_KINDS,
  MODERATION_STATES,
  NAME_DISPLAYS,
  NOTIFICATION_TYPES,
  NOTIFY_LEVELS,
  RANDOM_END_REASONS,
  REAL_NAME_VISIBILITIES,
  REPORT_REASONS,
  REPORT_STATUSES,
  REPORT_TARGETS,
  SANCTION_KINDS,
  SANCTION_SCOPES,
  THEMES,
  USER_ROLES,
  USER_STATUSES,
} from '@socketspace/shared/domain';

/** New IDs are UUID version 7: time-ordered, so new rows land at the end of indexes. */
export const newId = (): string => uuidv7();

/** Primary key column `id`, generated by the application when not supplied. */
export const idColumn = () => uuid('id').primaryKey().$defaultFn(newId);

/** A timestamp with time zone, read and written as a JavaScript `Date`. */
export const tstz = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });

export const createdAtColumn = () => tstz('created_at').notNull().defaultNow();
export const updatedAtColumn = () =>
  tstz('updated_at')
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

/** PostgreSQL's full-text search document type. */
export const tsvector = customType<{ data: string }>({
  dataType: () => 'tsvector',
});

// Enums (one database type per vocabulary in @socketspace/shared/domain)
export const userRoleEnum = pgEnum('user_role', USER_ROLES);
export const userStatusEnum = pgEnum('user_status', USER_STATUSES);
export const realNameVisibilityEnum = pgEnum('real_name_visibility', REAL_NAME_VISIBILITIES);
export const nameDisplayEnum = pgEnum('name_display', NAME_DISPLAYS);
export const avatarKindEnum = pgEnum('avatar_kind', AVATAR_KINDS);
export const dmPolicyEnum = pgEnum('dm_policy', DM_POLICIES);
export const themeEnum = pgEnum('theme', THEMES);
export const colorModeEnum = pgEnum('color_mode', COLOR_MODES);
export const conversationKindEnum = pgEnum('conversation_kind', CONVERSATION_KINDS);
export const conversationVisibilityEnum = pgEnum(
  'conversation_visibility',
  CONVERSATION_VISIBILITIES,
);
export const memberRoleEnum = pgEnum('member_role', MEMBER_ROLES);
export const notifyLevelEnum = pgEnum('notify_level', NOTIFY_LEVELS);
export const messageKindEnum = pgEnum('message_kind', MESSAGE_KINDS);
export const deletedByEnum = pgEnum('deleted_by', DELETED_BY);
export const moderationStateEnum = pgEnum('moderation_state', MODERATION_STATES);
export const attachmentStatusEnum = pgEnum('attachment_status', ATTACHMENT_STATUSES);
export const linkPreviewStatusEnum = pgEnum('link_preview_status', LINK_PREVIEW_STATUSES);
export const contactSourceEnum = pgEnum('contact_source', CONTACT_SOURCES);
export const contactRequestStatusEnum = pgEnum('contact_request_status', CONTACT_REQUEST_STATUSES);
export const notificationTypeEnum = pgEnum('notification_type', NOTIFICATION_TYPES);
export const randomEndReasonEnum = pgEnum('random_end_reason', RANDOM_END_REASONS);
export const reportTargetEnum = pgEnum('report_target', REPORT_TARGETS);
export const reportReasonEnum = pgEnum('report_reason', REPORT_REASONS);
export const reportStatusEnum = pgEnum('report_status', REPORT_STATUSES);
export const flagSourceEnum = pgEnum('flag_source', FLAG_SOURCES);
export const flagSeverityEnum = pgEnum('flag_severity', FLAG_SEVERITIES);
export const moderationActionKindEnum = pgEnum('moderation_action_kind', MODERATION_ACTION_KINDS);
export const sanctionKindEnum = pgEnum('sanction_kind', SANCTION_KINDS);
export const sanctionScopeEnum = pgEnum('sanction_scope', SANCTION_SCOPES);
