#!/usr/bin/env node
// Creates apps/web/.env.local and apps/realtime/.env.local for local development.
//
// - Addresses point at this computer (web app on :3000, realtime server on :4000, the local
//   PostgreSQL from `pnpm db:start` on :54329).
// - Secrets are generated here, randomly, for this computer only. They are written straight to the
//   files and never printed. They are NOT the production secrets, which the owner sets in the
//   hosting dashboards.
// - Existing files are never overwritten (delete one first to regenerate it).
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const secret = () => randomBytes(36).toString('base64url');

const database = 'postgres://socketspace@127.0.0.1:54329/socketspace';
const webUrl = 'http://localhost:3000';
const realtimeUrl = 'http://localhost:4000';
const internalSecret = secret();

const files = {
  'apps/web/.env.local': {
    DATABASE_URL: database,
    BETTER_AUTH_SECRET: secret(),
    BETTER_AUTH_URL: webUrl,
    REALTIME_PUBLIC_URL: realtimeUrl,
    INTERNAL_EVENTS_SECRET: internalSecret,
    EMAIL_DRIVER: 'file',
  },
  'apps/realtime/.env.local': {
    PORT: '4000',
    DATABASE_URL: database,
    WEB_ORIGINS: webUrl,
    AUTH_JWKS_URL: `${webUrl}/api/auth/jwks`,
    AUTH_ISSUER: webUrl,
    INTERNAL_EVENTS_SECRET: internalSecret,
    METRICS_TOKEN: secret(),
  },
};

const existing = Object.keys(files).filter((file) => existsSync(join(root, file)));
if (existing.length > 0 && existing.length < Object.keys(files).length) {
  // The two files share INTERNAL_EVENTS_SECRET, so they must be created together.
  console.error(
    `[setup] only some local env files exist (${existing.join(', ')}). Delete them and run again, ` +
      'so both get the same shared secret.',
  );
  process.exit(1);
}

for (const [file, values] of Object.entries(files)) {
  const path = join(root, file);
  if (existsSync(path)) {
    console.log(`[setup] ${file} already exists: left unchanged`);
    continue;
  }
  const body =
    '# Local development only. Generated by `pnpm setup:local`; never commit this file.\n' +
    Object.entries(values)
      .map(([key, value]) => `${key}=${value}`)
      .join('\n') +
    '\n';
  writeFileSync(path, body, { mode: 0o600 });
  console.log(
    `[setup] wrote ${file} (${String(Object.keys(values).length)} variables, values not shown)`,
  );
}
console.log('[setup] next: pnpm db:start && pnpm db:migrate:local, then pnpm dev');
